In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [17]:
## Sentences

sent = ['the glass of milk',
        'the glass of juice',
        'this is a perfect example',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understanding the meaning of works',
        'your videos are good'
        ]

In [18]:
## Defining the vocab size
vocab_size = 10000

In [19]:
## One Hot Representation

onehot_repr = [one_hot(words,vocab_size) for words in sent]
onehot_repr

[[9478, 1795, 5597, 1228],
 [9478, 1795, 5597, 1544],
 [8523, 2270, 4342, 7656, 2672],
 [9478, 9574, 5597, 8307],
 [3897, 4756, 4342, 3387, 4084],
 [3897, 4756, 4342, 3387, 8980],
 [643, 9478, 4730, 5597, 6467],
 [7153, 6662, 3152, 3387]]

In [20]:
## Word embedding representation

import numpy as np
sent_len = 8
embedded_docs = pad_sequences(onehot_repr,sent_len,padding='pre')
print(embedded_docs)

[[   0    0    0    0 9478 1795 5597 1228]
 [   0    0    0    0 9478 1795 5597 1544]
 [   0    0    0 8523 2270 4342 7656 2672]
 [   0    0    0    0 9478 9574 5597 8307]
 [   0    0    0 3897 4756 4342 3387 4084]
 [   0    0    0 3897 4756 4342 3387 8980]
 [   0    0    0  643 9478 4730 5597 6467]
 [   0    0    0    0 7153 6662 3152 3387]]


In [30]:
## Feature Representation

dim = 10 # dimension of the features

model = Sequential()
model.add(Embedding(vocab_size,dim,input_shape=(sent_len,)))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step


array([[[-0.01135042,  0.02292359, -0.04370489,  0.03300959,
          0.02192514,  0.02314639,  0.00657816,  0.02112309,
         -0.03301024, -0.04173402],
        [-0.01135042,  0.02292359, -0.04370489,  0.03300959,
          0.02192514,  0.02314639,  0.00657816,  0.02112309,
         -0.03301024, -0.04173402],
        [-0.01135042,  0.02292359, -0.04370489,  0.03300959,
          0.02192514,  0.02314639,  0.00657816,  0.02112309,
         -0.03301024, -0.04173402],
        [-0.01135042,  0.02292359, -0.04370489,  0.03300959,
          0.02192514,  0.02314639,  0.00657816,  0.02112309,
         -0.03301024, -0.04173402],
        [ 0.03669417,  0.01583827, -0.00526927, -0.0271486 ,
         -0.04214291,  0.04529082,  0.02735272, -0.00202026,
          0.03728161,  0.02957568],
        [-0.00582799, -0.04540509, -0.04086974, -0.01112479,
          0.01464409,  0.00501572, -0.01318661,  0.04367604,
         -0.00639112,  0.02196464],
        [-0.02583124, -0.01955491,  0.02277261, -0.0